
PostgreSQL:
  restart: always
  image: postgres:9.4
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=root
    - DB_PASS=root
    - DB_NAME=root
  volumes:
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
